//
// Created by joshua on 26.04.20.
//

#ifndef MY_ENCLAVE_XRA_ERROR_H
#define MY_ENCLAVE_XRA_ERROR_H
#define XRA_ERROR(X) (0x00000000|(X))
typedef enum _error{
    XRA_SUCCESS = XRA_ERROR(0x0000),
    XRA_MUTEX_LOCK_FAILED = XRA_ERROR(0x0001),
    XRA_MUTEX_UNLOCK_FAILED = XRA_ERROR(0x0002),
    XRA_CALLOC_FAILED = XRA_ERROR(0x0002),
    XRA_REALLOC_FAILED = XRA_ERROR(0x0003)
}xra_status_t;
#endif //MY_ENCLAVE_XRA_ERROR_H
